### ISSUE TITLE
intent.setType("vnd.android-dir/mms-sms") not working

### ISSUE THREAD

**Issue by apastel** [msmakhlouf/react-native-android-sms#2]
I installed the module today for purposes of using the `send()` feature with an empty address list.

I was noticing that  when I'd invoke `send()` from my react native code as you did in your example, nothing would happen, despite receiving a callback of `"OK"`. So I did a little research and replaced the `intent.setType("vnd.android-dir/mms-sms")` in `SmsModule.java` with `intent.setData(Uri.parse("sms:"))` and now it works.

A comment on this [stackoverflow post](http://stackoverflow.com/questions/2372248/launch-sms-application-with-an-intent) mentions that `intent.setType("vnd.android-dir/mms-sms")` may no longer work for Android 4.4 and up. A few people on there seem to disagree, however I can report that it did not work for me and I'm running Android 6.0.1.

**Comment by msmakhlouf** [comment]
fixed

**Comment by mabah** [comment]
thanks, fix

**Comment by raisahab-ritwik** [comment]
This did the trick. Thanks.
