### ISSUE TITLE
No list method

### ISSUE THREAD

**Issue by DarrylD** [msmakhlouf/react-native-android-sms#6]
This is the output of the module

<img width="220" alt="screen shot 2016-08-01 at 9 29 52 am" src="https://cloud.githubusercontent.com/assets/1310383/17295563/bcc534a8-57ca-11e6-8415-e2b2a2ffee55.png">

Only can send sms but no method to list them. Any fix for this?

**Comment by msmakhlouf** [comment]
there is a list method, I am guessing you did not pass a filter argument. if not kindly give me more details

**Comment by DarrylD** [comment]
no worries, fixed it, thx!
