### ISSUE TITLE
Module doesn't work on RN 0.29 >

### ISSUE THREAD

**Issue by briankabiro** [msmakhlouf/react-native-android-sms#8]
The module doens't work with newer React Native versions. Any plans to update?

**Comment by tmaly1980** [comment]
I'd love to know also

**Comment by briankabiro** [comment]
@tmaly1980 You can check out [react-native-get-sms-android](https://www.npmjs.com/package/react-native-get-sms-android)

**Comment by msmakhlouf** [comment]
pull request merged. very sorry for the ridiculous delay
